<div class="page-intro">
    <div>
        <h1>{{ $isSuperAdminView ? 'Report Monitoring Dashboard' : 'Admin Report Dashboard' }}</h1>
        <p>{{ $isSuperAdminView ? 'Monitor submitted accomplishment reports and review status activity across staff submissions.' : 'Review staff accomplishment reports, inspect the full report preview, and update review status without leaving the dashboard.' }}</p>
    </div>
    <div class="page-pill"><span>{{ $counts['employees'] }}</span><span>{{ $counts['employees'] === 1 ? 'report in scope' : 'reports in scope' }}</span></div>
</div>

{{-- Clickable cards give admins a quick dashboard summary and a fast status filter. --}}
<section class="summary-grid">
    <a href="{{ $reportRoutes['employees'] }}" class="summary-card summary-card-violet {{ in_array($mode, ['dashboard', 'reports', 'employees'], true) ? 'is-active' : '' }}" data-summary-card data-filter-value="all"><div><span class="summary-label">Submitted</span><div class="summary-value-row"><strong data-count-key="employees">{{ $counts['employees'] }}</strong><span>Reports</span></div><p class="summary-meta">All staff reports ready for review.</p></div><div class="summary-icon summary-icon-violet"><svg viewBox="0 0 24 24"><path d="M12 3 4 7v6c0 4.42 3.44 8.53 8 9 4.56-.47 8-4.58 8-9V7Zm0 2.2 6 3v4.8c0 3.2-2.39 6.45-6 6.93-3.61-.48-6-3.73-6-6.93V8.2Z"/></svg></div></a>
    <a href="{{ $reportRoutes['approved'] }}" class="summary-card summary-card-green {{ $mode === 'approved' ? 'is-active' : '' }}" data-summary-card data-filter-value="approved"><div><span class="summary-label">Approved</span><div class="summary-value-row"><strong data-count-key="approved">{{ $counts['approved'] }}</strong><span>Reports</span></div><p class="summary-meta">{{ $latestApprovedAt ? 'Latest approval: ' . \Illuminate\Support\Carbon::parse($latestApprovedAt)->format('M d, Y h:i A') : 'No approved reports yet.' }}</p></div><div class="summary-icon summary-icon-green"><svg viewBox="0 0 24 24"><path d="m9.55 17.45-4.5-4.5 1.4-1.4 3.1 3.08 7.99-8 1.42 1.42Z"/></svg></div></a>
    <a href="{{ $reportRoutes['pending'] }}" class="summary-card summary-card-orange {{ $mode === 'pending' ? 'is-active' : '' }}" data-summary-card data-filter-value="pending"><div><span class="summary-label">Pending</span><div class="summary-value-row"><strong data-count-key="pending">{{ $counts['pending'] }}</strong><span>Reports</span></div><p class="summary-meta">Waiting for admin review.</p></div><div class="summary-icon summary-icon-orange"><svg viewBox="0 0 24 24"><path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm1 11h4v2h-6V7h2Z"/></svg></div></a>
    <a href="{{ $reportRoutes['revisions'] }}" class="summary-card summary-card-red {{ $mode === 'revisions' ? 'is-active' : '' }}" data-summary-card data-filter-value="for_revision"><div><span class="summary-label">For Revision</span><div class="summary-value-row"><strong data-count-key="revisions">{{ $counts['revisions'] }}</strong><span>Reports</span></div><p class="summary-meta">Returned to staff for updates.</p></div><div class="summary-icon summary-icon-red"><svg viewBox="0 0 24 24"><path d="M12 6V3L8 7l4 4V8c2.76 0 5 2.24 5 5a5 5 0 0 1-8.66 3.46l-1.42 1.42A7 7 0 1 0 12 6Z"/></svg></div></a>
</section>
